# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100, verbose_name='имя')),
                ('middle_name', models.CharField(max_length=100, verbose_name='отчество')),
                ('last_name', models.CharField(max_length=100, verbose_name='фамилия')),
                ('phone', models.CharField(max_length=50, verbose_name='телефон')),
                ('message', models.TextField(blank=True, max_length=500, verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name=' фио мастера')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='контактный телефон')),
                ('master_photo', models.ImageField(upload_to='landing', verbose_name='фото мастера')),
            ],
            options={
                'verbose_name': 'мастер',
                'verbose_name_plural': 'мастера',
            },
        ),
        migrations.CreateModel(
            name='Work_Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_work_day', models.DateTimeField(verbose_name='начало рабочего дня')),
                ('end_work_day', models.DateTimeField(verbose_name='конец рабочего дня')),
                ('customer', models.CharField(max_length=50, verbose_name='занято')),
            ],
            options={
                'verbose_name': 'рабочее время',
                'verbose_name_plural': 'рабочее время',
            },
        ),
    ]
