# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='landing.Master'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='master',
            name='master_photo',
            field=models.ImageField(blank=True, upload_to='landing', verbose_name='фото мастера'),
        ),
    ]
