# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 23:53
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landing', '0004_auto_20170210_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=40, validators=[django.core.validators.RegexValidator(message='Введите телефонный номер в корректном формате (0XX) XXX-XX-XX', regex='(\\+38)?\\s*\\(?0\\d{2}\\)?\\s*\\d{3}\\s*[ \\-]?\\s*(\\d{2}\\s*[ \\-]?\\s*){2}')], verbose_name='Телефон')),
                ('photo', models.ImageField(blank=True, upload_to='clients', verbose_name='Аватарка')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
