# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20170212_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('building', models.CharField(max_length=100, verbose_name='Здание/дом')),
                ('additional', models.CharField(blank=True, max_length=200, verbose_name='Дополнительая информация')),
                ('office', models.CharField(max_length=250, verbose_name='Офис')),
                ('phone', models.CharField(max_length=25, unique=True, verbose_name='Телефон')),
                ('map_latitude', models.FloatField(blank=True, verbose_name='Широта')),
                ('map_longitude', models.FloatField(blank=True, verbose_name='Долгота')),
                ('vk', models.CharField(blank=True, max_length=250, verbose_name='VK')),
                ('instagram', models.CharField(blank=True, max_length=250, verbose_name='Instagram')),
            ],
        ),
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'verbose_name': 'Профиль клиента', 'verbose_name_plural': 'Профили клиентов'},
        ),
        migrations.AlterModelOptions(
            name='master',
            options={'verbose_name': 'Мастер', 'verbose_name_plural': 'Мастера'},
        ),
        migrations.AlterModelOptions(
            name='work_time',
            options={'verbose_name': 'Рабочее время', 'verbose_name_plural': 'Рабочее время'},
        ),
        migrations.AlterField(
            model_name='master',
            name='contact_phone',
            field=models.CharField(max_length=20, verbose_name='Контактный телефон'),
        ),
        migrations.AlterField(
            model_name='master',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='ФИО мастера'),
        ),
        migrations.AlterField(
            model_name='master',
            name='master_photo',
            field=models.ImageField(blank=True, upload_to='master', verbose_name='Фото мастера'),
        ),
    ]
