# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20170217_0334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.AlterField(
            model_name='address',
            name='instagram',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='address',
            name='map_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='address',
            name='map_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='address',
            name='vk',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='VK'),
        ),
    ]
