# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_auto_20170217_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='map_latitude',
            field=models.FloatField(blank=True, help_text='Для карты', null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='address',
            name='map_longitude',
            field=models.FloatField(blank=True, help_text='Для карты', null=True, verbose_name='Долгота'),
        ),
    ]
