# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20170127_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos', verbose_name='Изображение')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(max_length=250, verbose_name='Краткое описание')),
            ],
        ),
    ]
