# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20170207_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headimage',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Краткое описание'),
        ),
    ]
