# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20170207_0351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headimage',
            options={'verbose_name': 'Изображение в карусели', 'verbose_name_plural': 'Изображения в карусели'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фотография работы', 'verbose_name_plural': 'Фотографии работ'},
        ),
        migrations.AddField(
            model_name='photo',
            name='is_nail_polish',
            field=models.BooleanField(default=False, verbose_name='Лаки'),
        ),
    ]
