# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 18:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Отзыв')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('draft', models.BooleanField(editable=False, verbose_name='Модерирован')),
                ('user', models.ManyToManyField(editable=False, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
