# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='draft',
            field=models.BooleanField(default=True, editable=False, verbose_name='Модерирован'),
        ),
    ]
