# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20170127_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='Заголовок'),
        ),
    ]
