# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_feedback_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Заголовок'),
        ),
    ]
