# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_master_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='master',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='orders.Master', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(verbose_name='Время'),
        ),
    ]
