# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20170128_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Master', verbose_name='Мастер'),
        ),
    ]
